### PR TITLE
rewrite sock_op program with libbpf 1.0+

### PR DESCRIPTION
**Pull request by SirHao**
## Description

This commit rewrite the ``src/29-sockops`` with libbpf provided in ``third-party``, where current code cannot work. ( See [issue75](https://github.com/eunomia-bpf/bpf-developer-tutorial/issues/75))

Fixes # (issue) [75](https://github.com/eunomia-bpf/bpf-developer-tutorial/issues/75)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- [x] Complie, Load and Attach
```
$ make && ./load.sh
...load sucess...
$ bpftool prog show
107: sock_ops  name bpf_sockops_handler  tag e22e1120368ab3cc  gpl
        loaded_at 2023-12-06T13:04:56+0800  uid 0
        xlated 360B  jited 209B  memlock 4096B  map_ids 42,40
        btf_id 159
114: sk_msg  name bpf_redir  tag 907de5919d920159  gpl
        loaded_at 2023-12-06T13:04:56+0800  uid 0
        xlated 248B  jited 167B  memlock 4096B  map_ids 40
        btf_id 165
```
- [x] Iperf with bpf_output and tcpdump
```
./trace_bpf_output.sh # trace the output of sock_op
```
After start iperf as below, we can see the output of connection tracing from the script above
```
$ nohup iperf -s &
$ iperf -c 127.0.0.1
```

**Test Configuration**:

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by SirHao** [comment]
@yunwei37 Can u please help me to review this PR? Thanks a lot

**Comment by yunwei37** [comment]
Thanks a lot for your contribution!

**Review by yunwei37 — APPROVED** [review]

**Comment by yunwei37** [comment]
Would you like to update the CI in GitHub actions so it can be tested automatically?

**Comment by yunwei37** [comment]
Examples can be found in https://github.com/eunomia-bpf/bpf-developer-tutorial/blob/main/.github/workflows/test-libbpf.yml

**Comment by yunwei37** [comment]
That's ok. Maybe you can add another workflow to test it. You can use commands you like and not limited to makefile.

If you are not familiar with GitHub actions, I can merge this first : ) That's ok

**Comment by SirHao** [comment]
> That's ok. Maybe you can add another workflow to test it. You can use commands you like and not limited to makefile.
> 
> If you are not familiar with GitHub actions, I can merge this first : ) That's ok

@yunwei37  I am indeed not familiar with Github action. Thus I have made a double check in another one environment and this project still can works. Just merge it please~

**Comment by yunwei37** [comment]
Ok. Thanks again!

**Pull request merged**
